### ISSUE TITLE
Copy paste

### ISSUE THREAD

**Issue by mattddowney** [laughedelic/pisces#6] opened 2016-05-27 18:33 UTC
Copy pasting creates undesired behavior.

Pasting the following into my terminal:
`echo -e "\e[1;31mSome red message\e[0m"`

Will result in:
`echo -e "\e[1;31mSome red message\e[0m""]]"`

At first I thought it might be my terminal, but the behavior exists whether I use terminator, xterm, or the default terminal for Xubuntu 16.04.

**Comment by laughedelic** [comment] 2016-05-27 18:40
@mattddowney I see this problem on fish 2.3.0. And yes, it's not about terminal.. Which version of fish do you use?

**Comment by mattddowney** [comment] 2016-05-27 19:20
2.3.0.

Digging into this, it looks like what might need to happen is to compare the contents of the clipboard with the input. IE:

`xsel --clipboard`

**Comment by laughedelic** [comment] 2016-07-07 20:09
Hi @mattddowney. Have you come up with any solution/workaround?

**Comment by mattddowney** [comment] 2016-07-12 03:28
I looked into it, but wasn't able to get anything working that didn't cause more bugs

**Comment by laughedelic** [comment] 2017-08-02 16:56
Hi @mattddowney! I think I have good news regarding this issue. 

I recently updated to fish 2.6 and noticed that I can't reproduce this bug, because they implemented **bracketed (a.k.a safe) paste in v2.6** 🎉  From the [v2.6 release notes](https://github.com/fish-shell/fish-shell/releases/tag/2.6.0):

> Under terminals which support it, bracketed paste is enabled, escaping problematic characters for security and convience ([#3871](https://github.com/fish-shell/fish-shell/pull/3871)). Inside single quotes ('), single quotes and backslashes in pasted text are escaped ([#967](https://github.com/fish-shell/fish-shell/issues/967)). The fish_clipboard_paste function (bound to C-v by default) is still the recommended pasting method where possible as it includes this functionality and more.

I just tested on clean environment different versions and observed that the problem persists up to fish 2.5, but disappears in 2.6. So I'm going to close it. Anyway, if you can upgrade to fish 2.6 and confirm that the issue is not relevant anymore, please write here a comment 😉

**Closed** 2017-08-02 16:56 UTC
Labels: bug

**Comment by mattddowney** [comment] 2017-08-02 17:20
Updated to 2.6.0

Issue is gone in Terminator and XTerm, however, the issue persists in VSCode's integrated terminal (v1.14.2). Pretty sure this is something upstream though, because C-v works fine, but right click > paste does not.

But it seems to mostly work, so that's awesome. Thanks for keeping up with this!

**Comment by laughedelic** [comment] 2017-08-02 17:35
Cool! Thanks for the info. I'm glad that it's (mostly) solved for you. Can't say anything about VSCode though, but as you say, it should be something upstream..
